input {
  beats {
    port => 5044
  }
}

filter {

  if [container][name] =~ /exporter/ {
    mutate { add_field => { "service" => "exporter" } }
  }

  else if [container][name] =~ /nginx/ {
    grok {
      match => {
        "message" => '%{IPORHOST:client_ip} - %{USER:user} \[%{HTTPDATE:timestamp}\] "%{WORD:method} %{URIPATHPARAM:path} HTTP/%{NUMBER:http_version}" %{NUMBER:status_code} %{NUMBER:bytes}'
      }
    }
    mutate { add_field => { "service" => "nginx" } }
  }

  else if [container][name] =~ /backend/ {
    json {
      source => "message"
    }
    mutate { add_field => { "service" => "nodejs" } }
  }

  else if [container][name] =~ /python-analysis/ {
    mutate { add_field => { "service" => "python-analysis" } }
  }

  else if [container][name] =~ /my-postgres/ {
    mutate { add_field => { "service" => "postgres" } }
  }

  else if [container][name] =~ /my-redis/ {
    mutate { add_field => { "service" => "redis" } }
  }

  else if [container][name] =~ /prometheus/ {
    mutate { add_field => { "service" => "prometheus" } }
  }

  else if [container][name] =~ /grafana/ {
    mutate { add_field => { "service" => "grafana" } }
  }
  else {
    mutate { add_field => { "service" => "other" } }
  }

  mutate {
    remove_field => ["agent", "ecs", "host", "input"]
  }

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{[service]}-%{+YYYY.MM.dd}"
    action => "create"
  }
}